name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Mise (or directly Rustup) for toolchain management
      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.7.27
          install: true

      - name: Use project-defined tools with Mise
        run: mise install
        
      - name: Install Rust components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Check formatting
        run: make fmt

      - name: Run clippy lints
        run: make lint

      - name: Run tests
        run: make test

      - name: Build project (debug)
        run: make build